# Generated by Django 5.2.13 on 2026-04-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundali',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='palmreading',
            name='payment_status',
            field=models.BooleanField(default=False),
        ),
    ]
