# Generated by Django 5.2.13 on 2026-04-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrology', '0002_alter_kundali_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kundali',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='palmreading',
            name='phone',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
